### ISSUE TITLE
Controller create method

### ISSUE THREAD

**Issue by hahunavth** [ToilaAn/pj_ltct#4]
## Files:
- importHistory.controller.js
- supplier.comtroler.js

## Todo:
- [x] Cần tạo model instance từ request.body thay vì dùng object có sẵn (biến list)
- [x] Validate request.body
- [x] Test api bằng swagger

![image](https://user-images.githubusercontent.com/66118664/204517243-0324ecaa-96fe-4fe3-8ed5-257335acdc03.png)
